### ISSUE TITLE
Recomposition issue

### ISSUE THREAD

**Issue by RezaNazari66** [krzdabrowski/android-starter-2022#68] opened 2024-01-22 21:08 UTC
![image](https://github.com/krzdabrowski/android-starter-2022/assets/30935854/2e8ed99c-6368-4977-8fc1-e720dc2d1ec4)

By each change in any state, whole the screen will recompose

**Comment by krzdabrowski** [comment] 2024-02-04 17:03
Hello, thanks for your contribution!

If by "each change in any state" you mean the action of refreshing the screen via pull-to-refresh functionality, isn't that "a feature, not a bug"? 🙂

To visually show that pull-to-refresh works, I randomise the `imageUrl` for each rocket (API returns few URLs for each), see: `fun RocketResponse.toDomainModel()`.`imageUrl` is part of `RocketDisplayable` that represents UI model for each item (hence recomposition for each `RocketItem`).
Going forward, each `RocketDisplayable` is part of `rockets` field in `RocketsUiState`. This UiState is used in both `RocketsScreen` and collected in `RocketsRoute`. `UiState` is changed on each pull-to-refresh action hence recomposition here seems rational too 😅 

Happy to hear more details if you still find this as an issue 🙂

**Comment by krzdabrowski** [comment] 2024-02-04 18:30
Actually not, it is a good improvement (but of course a little "bad-looking"), see more 
here: https://multithreaded.stitchfix.com/blog/2022/08/05/jetpack-compose-recomposition/

I might add it to the project in the future but if you don't have any more issues with the project per-se, I'd close this issue 😊

**Closed** 2024-02-06 17:01 UTC
